### ISSUE TITLE
Grappling hook not working properly #72

### ISSUE THREAD

**Issue by cooldown14** [MCreator-Examples/Feedback#145]
The hook is not working correctly. I am using MCreator 2022.3 and modding for Minecraft forge 1.18.2.

When the hook is used, it breaks the block it hits and then begins to descend.

I have noticed that this has been happening for several versions. This is annoying because it prevents you from using it to climb vertical walls, only for places where there is a ceiling.

Example:

![2022-12-11_01 30 01](https://user-images.githubusercontent.com/120286504/206880832-72297e49-9672-49b9-b8e1-218a5a62fe0c.png)

or

[https://ibb.co/qWLGRDf](url)

**Comment by northwesttreesgaming** [comment]
Thanks for letting me know I will try to figure out a workaround.
Most likely something changed in the Minecraft or Forge API that broke the old procedure script.

**Comment by northwesttreesgaming** [comment]
I found the issue, I think the system for projectile block trigger location changed so what was happening was rather than the block running from the side it hit it was running from in the block it hit so I am just adding a catch and I will add new version for 2022.3 for 1.19.2, it should also be fixed for 1.18.2 for the same MCR version as it looks to be doing the same thing. I will upload the version tomorrow after I am done with uploading.

**Comment by cooldown14** [comment]
Okay, thank you. You were super fast! You're great.

**Comment by northwesttreesgaming** [comment]
I updated the download page it can be downloaded below.
https://github.com/MCreator-Examples/Projects/discussions/72

Huge thanks for letting me know 💖

**Comment by cooldown14** [comment]
Now works great! (On 1.18.2 too!) 

Thanks to you for sure, you do a really good job with your videos.
