### ISSUE TITLE
[NEW TUTORIAL] Custom Entity Animations and Resizing Models

### ISSUE THREAD

**Issue by ImDaMilan** [MCreator-Examples/Feedback#20]
Hi, I've already posted a request here, and you responded and made it a video, and I'm super thankful for that! I've got one more thing that I would like to see, regarding custom entities, and MCreator forums have sadly been unhelpful about it. That is regarding entity models, I know how to make them in Blockbench, but I want to know how to be able to resize them and add animations.

## DESCRIPTION (Required)
>1.  A lot of people have been wanting to know how to make entity animations, and resize vanilla and custom entity models.
>1.  I want to see how you can resize vanilla models, that are in MCreator, and add animations to custom entity models.

## LIST OF KEY FEATURES (Required)
> Describe any new features you want to be added.

* [ ] To see how you can resize vanilla models (I'm particularily interested in a mob that has the same model as a slime, but a different texture, and how you can set it's size).
* [ ] To see how you can add custom animations to custom entity models without GeckoLib becouse it's outdated.

I hope you will be able to help, but nevertheless, you are awesome no matter what you do, and thank you for the previous request! :D

**Comment by northwesttreesgaming** [comment]
Sorry for the late reply, I have been a bit busy with some things.

Currently GekoLib is not supported with MCreator, I have actually talked to them on their get hub and it seems they do not want to add support for single animation models which is what MCreator needs, they said they did not have time to do that.

Goldorion has wanted to make a built in animation program for MCreator as this would be really useful for the community however from what I understand what he has said its really complex to make so I am not sure when or if it will happen.

Regarding the resizing vanilla entity models. I don't think this is possible either, you can create models or use a addon in Blockbench to create the model then rescale the meshes, however this would also require you to adjust the position as they don't scale up really well as the position stays the same.

At the moment I don't think there is much I can do regarding this request, most animation things right now are limited to say the least due to GekoLib adding a separate animation file, and mcreator is harder to adapt to this change then if they where to adapt to us, also there is some forge bios in their team so the odds of them adding support for MCreator is really low.

I will keep this issue open incase it becomes possible to do but I don't expect it any time soon to change.
